apiVersion: v1
kind: Service
metadata:
  name: phxclus
  labels:
    app: phxgcpcluster
    tier: phxclus
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: phxgcpcluster
    tier: phxclus
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: phxclus
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: phxgcpcluster
    tier: phxclus
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 3
  # selector can be applied automatically
  # from the labels in the pod template if not set
  template:
    metadata:
      labels:
        app: phxgcpcluster
        tier: phxclus
    spec:
      containers:
      - name: phxgcpcluster
        # image: phxgcpcluster:latest
        image: gcr.io/flowing-silo-192900/phx_gcp_cluster:v2
        # image: gcr.io/base-154519/phxgcpcluster:0.0.3
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: "8080"
        - name: MY_BASENAME
          value: phxgcpcluster
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REPLACE_OS_VARS
          value: "true"
        - name: RELEASE_CONFIG_DIR
          value: /beamconfig
        - name: ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: app-config
              key: erlang-cookie
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /beamconfig
      volumes:
      - name: config-volume
        configMap:
          name: vm-config
